name: Dev image
id: dev
stages:
  - id: build
    base: fedora:latest
    singlelayer: false
    labels:
      maintainer: Dharun Krishna K B
    modules:
      - name: install-pkgs
        type: dnf
        source:
          packages:
            - cargo
            - conda
            - distrobox
            - elixir
            - fastfetch
            - gcc
            - gcc-gfortran
            - g++
            - gjs
            - gjs-devel
            - golang
            - htop
            - java-devel
            - java-openjdk
            - lua
            - nano
            - nodejs
            - perl-core
            - php-cli
            - podman
            - python3
            - R
            - ranger
            - ruby
            - rust
            - sqlite
            - sqlite-devel
            - sqlite-tcl
            - swiftlang
            - tldr
            - vim
